from __future__ import annotations

from typing import TypeAlias
from collections.abc import Sequence

import delta
from delta import DType, Device, Tensor

NestedFloat: TypeAlias = float | Sequence["NestedFloat"]


def tensor(obj: NestedFloat, device: Device = delta.cpu) -> Tensor: ...
def randn(shape: list[int], device: Device = delta.cpu) -> Tensor: ...
def zeros(shape: list[int], dtype: DType, device: Device = delta.cpu) -> Tensor: ...
def zeros_like(tensor: Tensor, dtype: DType, device: Device = delta.cpu) -> Tensor: ...
def ones(shape: list[int], dtype: DType, device: Device = delta.cpu) -> Tensor: ...
def ones_like(tensor: Tensor, dtype: DType, device: Device = delta.cpu) -> Tensor: ...
def eye(n: int, dtype: DType, device: Device = delta.cpu) -> Tensor: ...
def arange(start: float, end: float, step: float, dtype: DType, device: Device = delta.cpu) -> Tensor: ...
