from typing import Sequence
from delta import Tensor

class SGD:
    @property
    def lr(self) -> float: ...

    @property
    def is_maximizing(self) -> bool: ...

    def __init__(self, parameters: Sequence[Tensor], lr: float) -> None: ...
    def step(self) -> None: ...
    def zero_grad(self) -> None: ...
    def change_lr(self, gamma: float) -> None: ...
    def maximize(self) -> None: ...
    def minimize(self) -> None: ...