from __future__ import annotations
from enum import Enum
from delta import Tensor

class Parameter:
    @property
    def shape(self) -> list[int]: ...
    @property
    def data(self) -> Tensor: ...
    def __new__(cls, tensor: Tensor) -> Parameter: ...
    def grad(self) -> list[float] | None: ...
    def item(self) -> list[float]: ...

def relu(x: Tensor) -> Tensor: ...
def sigmoid(x: Tensor) -> Tensor: ...
def softmax(x: Tensor, dim: int = -1) -> Tensor: ...

class Reduction(Enum):
    SUM: Reduction
    MEAN: Reduction

class MSELoss:
    def __new__(cls, reduction: Reduction | None = Reduction.MEAN) -> MSELoss: ...
    def measure(self, a: Tensor, b: Tensor) -> Tensor: ...
    def __call__(self, a: Tensor, b: Tensor) -> Tensor: ...
