# delta/_delta.pyi
from __future__ import annotations
from typing import Optional

class Tensor:
    shape: list[int]
    stride: list[int]

    # ── Constructors ────────────────────────────────────────────────────────
    @staticmethod
    def tensor(data: list[float], shape: list[int]) -> Tensor: ...
    @staticmethod
    def randn(shape: list[int]) -> Tensor: ...
    @staticmethod
    def zeros(shape: list[int]) -> Tensor: ...
    @staticmethod
    def zeros_like(tensor: Tensor) -> Tensor: ...
    @staticmethod
    def ones(shape: list[int]) -> Tensor: ...
    @staticmethod
    def ones_like(tensor: Tensor) -> Tensor: ...
    @staticmethod
    def arange(start: float, end: float, step: float) -> Tensor: ...
    @staticmethod
    def cat(tensors: list[Tensor], dim: int) -> Tensor: ...

    # ── Metadata ────────────────────────────────────────────────────────────
    def length(self) -> int: ...
    def storage(self) -> list[float]: ...
    def item(self) -> list[float]: ...
    def grad(self) -> list[float] | None: ...
    def requires_grad(self, value: bool) -> Tensor: ...

    # ── Shape manipulation ───────────────────────────────────────────────────
    def reshape(self, shape: list[int]) -> Tensor: ...
    def view(self, shape: list[int]) -> Tensor: ...
    def transpose(self, dim0: int, dim1: int) -> Tensor: ...
    def t(self) -> Tensor: ...
    def unsqueeze(self, dim: int) -> Tensor: ...
    def squeeze(self, dim: list[int]) -> Tensor: ...
    def expand(self, new_shape: list[int]) -> Tensor: ...

    # ── Reduction ───────────────────────────────────────────────────────────
    def sum(self, dim: Optional[int] = None, keepdim: bool = False) -> Tensor: ...
    def mean(self, dim: Optional[int] = None, keepdim: bool = False) -> Tensor: ...

    # ── Element-wise ops ────────────────────────────────────────────────────
    def exp(self) -> Tensor: ...
    def pow(self, n: int) -> Tensor: ...

    # ── Autograd ────────────────────────────────────────────────────────────
    def backward(self) -> None: ...

    # ── Arithmetic operators ─────────────────────────────────────────────────
    def __add__(self, other: float | int | Tensor) -> Tensor: ...
    def __radd__(self, other: float | int | Tensor) -> Tensor: ...
    def __sub__(self, other: float | int | Tensor) -> Tensor: ...
    def __rsub__(self, other: float | int | Tensor) -> Tensor: ...
    def __mul__(self, other: float | int | Tensor) -> Tensor: ...
    def __rmul__(self, other: float | int | Tensor) -> Tensor: ...
    def __truediv__(self, other: float | int | Tensor) -> Tensor: ...
    def __rtruediv__(self, other: float | int | Tensor) -> Tensor: ...
    def __neg__(self) -> Tensor: ...

    # ── Display ──────────────────────────────────────────────────────────────
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

# ── Module-level functions ───────────────────────────────────────────────────
def tensor(data: list[float], shape: list[int]) -> Tensor: ...
def randn(*shape: int) -> Tensor: ...
def zeros(*shape: int) -> Tensor: ...
def ones(*shape: int) -> Tensor: ...
def matmul(a: Tensor, b: Tensor) -> Tensor: ...
def cross(a: Tensor, b: Tensor) -> Tensor: ...
def sum(input: Tensor, dim: Optional[int] = None, keepdim: bool = False) -> Tensor: ...
def mean(input: Tensor, dim: Optional[int] = None, keepdim: bool = False) -> Tensor: ...
def cat(tensors: list[Tensor], dim: int) -> Tensor: ...
