from __future__ import annotations

from typing import TypeAlias
from collections.abc import Sequence

from delta import Tensor

NestedFloat: TypeAlias = float | Sequence["NestedFloat"]


def tensor(obj: NestedFloat) -> Tensor: ...
def randn(shape: list[int]) -> Tensor: ...
def zeros(shape: list[int]) -> Tensor: ...
def zeros_like(tensor: Tensor) -> Tensor: ...
def ones(shape: list[int]) -> Tensor: ...
def ones_like(tensor: Tensor) -> Tensor: ...
def eye(n: int) -> Tensor: ...
def arange(start: float, end: float, step: float) -> Tensor: ...
