[package]
name = "delta-cuda"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
readme = "README.md"
repository.workspace = true
license-file.workspace = true

[dependencies]
# internal crates
delta-core = { workspace = true }
delta-cpu = { workspace = true }
# external crates
cudarc = { workspace = true }
float8 = { workspace = true }
half = { workspace = true }

[lints]
workspace = true
