[package]
name = "delta-cuda"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
readme = "README.md"
repository.workspace = true
license-file.workspace = true

[dependencies]
cudarc = { workspace = true }
delta-core = { workspace = true }
delta-cpu = { workspace = true }

[lints]
workspace = true
