[package]
name = "delta-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
readme = "README.md"
repository.workspace = true
license-file.workspace = true

[dependencies]

num-traits = { workspace = true }
float8 = { workspace = true }
half = { workspace = true }

[lints]
workspace = true
