[package]
name = "delta"
# versions
version = "0.1.0"
edition = "2024"
rust-version = "1.95.0"
# info
authors = ["commanderxa"]
readme = "README.md"
repository = "https://github.com/CommanderXA/delta"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
cuda = ["dep:cudarc"]

[dependencies]
delta-macros = { path = "../delta-macros" }

rand = "0.10.1"
cudarc = { version = "0.19", optional = true, features = [
    "cublas",
    "cuda-version-from-build-system",
    "f8",
    "f16",
] }
half = { version = "2.7.1", features = ["alloc", "num-traits"] }
float8 = { version = "0.7.0", features = ["num-traits"] }
num-traits = { version = "0.2.19", default-features = false }

[lib]
name = "delta"
path = "src/lib.rs"
crate-type = ["rlib"]
