from typing import Optional, Sequence

class Tensor:
    def __add__(self, other: float | "Tensor") -> "Tensor": ...
    def __radd__(self, other: float | "Tensor") -> "Tensor": ...
    def __sub__(self, other: float | "Tensor") -> "Tensor": ...
    def __mul__(self, other: float | "Tensor") -> "Tensor": ...
    def __truediv__(self, other: float | "Tensor") -> "Tensor": ...
    def __neg__(self) -> "Tensor": ...

    def reshape(self, *shape: int) -> "Tensor": ...
    def sum(self, dim: Optional[int] = None, keepdim: bool = False) -> "Tensor": ...
    def mean(self, dim: Optional[int] = None, keepdim: bool = False) -> "Tensor": ...
    def backward(self) -> None: ...
    def grad(self) -> list[float] | None: ...

def tensor(data) -> Tensor: ...
def sum(input: Tensor, dim: Optional[int] = None, keepdim: bool = False) -> Tensor: ...
def mean(input: Tensor, dim: Optional[int] = None, keepdim: bool = False) -> Tensor: ...
def cat(tensors: Sequence[Tensor], dim: int = 0) -> Tensor: ...
