from .. import Tensor

class Linear:
    def __init__(self, in_features: int, out_features: int, bias: bool = True) -> None: ...
    def forward(self, x: Tensor) -> Tensor: ...
    def __call__(self, x: Tensor) -> Tensor: ...