name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check whether Cargo.toml version changed
        id: version_check
        run: |
          if git diff HEAD~1 HEAD -- Cargo.toml | grep '^[+-]version = '; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "changed=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Show result
        run: echo "version changed = ${{ steps.version_check.outputs.changed }}"

      - name: Update rust
        if: steps.version_check.outputs.changed == 'true'
        run: rustup update

      - name: Output rust version
        if: steps.version_check.outputs.changed == 'true'
        run: rustup --version

      - uses: actions/checkout@v3

      - name: Build
        if: steps.version_check.outputs.changed == 'true'
        run: cargo build --verbose

      - name: Run tests
        if: steps.version_check.outputs.changed == 'true'
        run: cargo test --verbose
